name: Train and Test Model

on:
  push:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install wandb scikit-learn numpy pandas
    - name: Login to Wandb
      run: wandb login ${{ secrets.WANDB_API_KEY }}
    - name: Train and Test Model
      run: python model.py
